### ISSUE TITLE
rase_db_prepare_tree.py not found in ./rase-db-spneumoniae-sparc/tree

### ISSUE THREAD

**Issue by rica01** [c2-d2/rase-db-spneumoniae-sparc#3]
Hello.

I am trying to install the RASE DB and during the makefile run i found this error:

`make[1]: Entering directory '/mnt/compgen/homes/ricardo/sepsis/case_pseudomona/rase-db-spneumoniae-sparc/tree'
rase_db_prepare_tree.py \
        -i ../published/SPARC.core_genes.tree \
        -o tree.newick \
        -m ../published/isolates.2013.tsv \
        -n 2 \
        -t 2 \
        -p 3
bash: line 1: rase_db_prepare_tree.py: command not found
`

I am guessing this rase_db_prepare_tree.py is in another package? Would anyone point me to it please

Thank you.

-Ricardo

**Comment by karel-brinda** [comment]
It's part of the RASE package (https://github.com/c2-d2/rase), which is included as a submodule within this repo. The directories are then added to path by this line: https://github.com/c2-d2/rase-db-spneumoniae-sparc/blob/master/init.mk#L10

**Comment by karel-brinda** [comment]
Try running these two commands:
```
git submodule init
git submodule update
```

**Comment by rica01** [comment]
Worked.
Thank you.
