### ISSUE TITLE
Some FASTA files needed for k-mer propagation are probably missing

### ISSUE THREAD

**Issue by rica01** [c2-d2/rase-db-spneumoniae-sparc#4]
Hello.

I am still trying to get this up and running but I got stopped by another error. This time it seems that I am missing some files?

```

[prophyle] 2021-02-24 22:10:38 Running k-mer propagation
make[2]: *** No rule to make target '/mnt/compgen/homes/ricardo/sepsis/case_pseudomona/rase-db-spneumoniae-sparc/isolates/R34-3063.fa', needed by 'R34-3063.full.fa.complete'.  Stop.
[prophyle] 2021-02-24 22:10:38 Unfinished, an error occurred (error code 2, 0.8 MB used): make -C spneumoniae-sparc.k18/propagation -n -s > /dev/null
Error: Some FASTA files needed for k-mer propagation are probably missing, see the messages above.
Makefile:16: recipe for target '.index.18.complete' failed

```

**Comment by karel-brinda** [comment]
What database are you currently constructing? If it's the S. pneumoniae database from this repository, than it says that the following file is missing: https://github.com/c2-d2/rase-db-spneumoniae-sparc/blob/master/isolates/R34-3063.fa. 

If the goal is to create a new database, it should be done through the skeleton: https://github.com/c2-d2/rase-db-skeleton.

**Comment by rica01** [comment]
> What database are you currently constructing? If it's the S. pneumoniae database from this repository, than it says that the following file is missing: https://github.com/c2-d2/rase-db-spneumoniae-sparc/blob/master/isolates/R34-3063.fa.
> 
> If the goal is to create a new database, it should be done through the skeleton: https://github.com/c2-d2/rase-db-skeleton.

I am building the pneumoniae indeed. But that file, should it come with the repo? or should I get it elsewhere?

**Comment by karel-brinda** [comment]
That file is a part of this repo. It's one of the genomes in this specific database.

**Comment by rica01** [comment]
> That file is a part of this repo. It's one of the genomes in this specific database.

Thank you prof. Karel. 
I found a script that I did not run to download the files needed. I am putting up together a mini setup guide, I don't know if it would be useful for you, but I can send it to you when I'm done. 

Thank you again.

-Ricardo

**Comment by karel-brinda** [comment]
Hi Richardo, hope that everything works as it should. Sure, I would be definitely interested in the setup guide! Please send it to karel.brinda@gmail.com. Thanks!
